
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ColorToResistance extends javax.swing.JFrame {

    private String Fnumber = " " ;
    private String Snumber = " " ;
    private String Multiplier = " ";
    private String Tolerance = " ";
    private JFrame frame;
    
    
    /**
     * Creates new form ColorToResistance
     * 
     * 
     */
    
    public ColorToResistance() {
        
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ResistorValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ResistorTol = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MaximumRange = new javax.swing.JTextField();
        LBand1 = new javax.swing.JLabel();
        LBand2 = new javax.swing.JLabel();
        LBand3 = new javax.swing.JLabel();
        LBand4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MinimumRange = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CalculateButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        Selector = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        BlackButton = new javax.swing.JButton();
        BrownButton = new javax.swing.JButton();
        OrangeButton = new javax.swing.JButton();
        RedButton = new javax.swing.JButton();
        YellowButton = new javax.swing.JButton();
        GreenButton = new javax.swing.JButton();
        BlueButton = new javax.swing.JButton();
        VioletButton = new javax.swing.JButton();
        GrayButton = new javax.swing.JButton();
        WhiteButton = new javax.swing.JButton();
        GoldButton = new javax.swing.JButton();
        SilverButton = new javax.swing.JButton();
        NoneButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4), "Colour To Resistance", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Algerian", 0, 18), new java.awt.Color(255, 255, 0))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Minimum Range");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(110, 350, 137, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Resistor Value");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 130, 120, 30);

        ResistorValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(ResistorValue);
        ResistorValue.setBounds(181, 130, 140, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tolerance");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(jLabel2);
        jLabel2.setBounds(50, 170, 120, 30);

        ResistorTol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(ResistorTol);
        ResistorTol.setBounds(181, 170, 140, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Maximum Range");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 250, 120, 30);

        MaximumRange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(MaximumRange);
        MaximumRange.setBounds(181, 250, 140, 28);
        jPanel4.add(LBand1);
        LBand1.setBounds(130, 60, 10, 40);
        jPanel4.add(LBand2);
        LBand2.setBounds(150, 60, 10, 40);

        LBand3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel4.add(LBand3);
        LBand3.setBounds(170, 60, 10, 40);

        LBand4.setBackground(new java.awt.Color(204, 255, 153));
        jPanel4.add(LBand4);
        LBand4.setBounds(200, 60, 10, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Minimum Range");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(jLabel4);
        jLabel4.setBounds(50, 210, 120, 30);

        MinimumRange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.add(MinimumRange);
        MinimumRange.setBounds(181, 210, 140, 28);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TheResistor - cc.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(90, 45, 170, 70);

        CalculateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        Selector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Selector.setText("Choose First Colour");
        Selector.setToolTipText("");
        Selector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2), "Colours", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        BlackButton.setBackground(new java.awt.Color(0, 0, 0));
        BlackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BlackButton.setForeground(new java.awt.Color(255, 255, 255));
        BlackButton.setText("Black");
        BlackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BlackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackButtonActionPerformed(evt);
            }
        });

        BrownButton.setBackground(new java.awt.Color(255, 153, 153));
        BrownButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BrownButton.setText("Brown");
        BrownButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 2));
        BrownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrownButtonActionPerformed(evt);
            }
        });

        OrangeButton.setBackground(new java.awt.Color(255, 204, 0));
        OrangeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OrangeButton.setText("Orange");
        OrangeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        OrangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrangeButtonActionPerformed(evt);
            }
        });

        RedButton.setBackground(new java.awt.Color(255, 51, 51));
        RedButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RedButton.setText("Red");
        RedButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        RedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedButtonActionPerformed(evt);
            }
        });

        YellowButton.setBackground(new java.awt.Color(255, 255, 0));
        YellowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        YellowButton.setText("Yellow");
        YellowButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        YellowButton.setFocusable(false);
        YellowButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        YellowButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        YellowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YellowButtonActionPerformed(evt);
            }
        });

        GreenButton.setBackground(new java.awt.Color(0, 255, 0));
        GreenButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GreenButton.setText("Green");
        GreenButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 2));
        GreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenButtonActionPerformed(evt);
            }
        });

        BlueButton.setBackground(new java.awt.Color(0, 0, 255));
        BlueButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BlueButton.setText("Blue");
        BlueButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        BlueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueButtonActionPerformed(evt);
            }
        });

        VioletButton.setBackground(new java.awt.Color(255, 0, 204));
        VioletButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VioletButton.setText("Violet");
        VioletButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 204), 2));
        VioletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VioletButtonActionPerformed(evt);
            }
        });

        GrayButton.setBackground(new java.awt.Color(102, 102, 102));
        GrayButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GrayButton.setText("Gray");
        GrayButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        GrayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayButtonActionPerformed(evt);
            }
        });

        WhiteButton.setBackground(new java.awt.Color(255, 255, 255));
        WhiteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        WhiteButton.setText("White");
        WhiteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        WhiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhiteButtonActionPerformed(evt);
            }
        });

        GoldButton.setBackground(new java.awt.Color(255, 204, 51));
        GoldButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GoldButton.setText("Gold");
        GoldButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        GoldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoldButtonActionPerformed(evt);
            }
        });

        SilverButton.setBackground(new java.awt.Color(153, 153, 153));
        SilverButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SilverButton.setText("Silver");
        SilverButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        SilverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilverButtonActionPerformed(evt);
            }
        });

        NoneButton.setBackground(new java.awt.Color(238, 238, 240));
        NoneButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoneButton.setText("None");
        NoneButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 234, 237), 2));
        NoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BlackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BrownButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(YellowButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlueButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VioletButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GrayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WhiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GoldButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SilverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NoneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(BlackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(BrownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YellowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VioletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WhiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SilverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CalculateButton))))
                        .addGap(33, 33, 33)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Selector, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(CalculateButton)
                        .addGap(35, 35, 35)
                        .addComponent(ClearButton)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ExitButton)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jMenu1.setText("File");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Go to  resistance to colour calculator");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setText("Help");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        jMenuItem2.setText("Close All Program");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     
    }//GEN-LAST:event_formWindowActivated

    private void SelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorActionPerformed

    }//GEN-LAST:event_SelectorActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
     
   Selector.setText("Choose First Colour");
   
    LBand1.setOpaque(false);
    LBand1.setBackground(Color.CYAN);
    LBand2.setOpaque(false);
    LBand2.setBackground(Color.CYAN);
    LBand3.setOpaque(false);
    LBand3.setBackground(Color.CYAN);
    LBand4.setOpaque(false);
    LBand4.setBackground(Color.CYAN);
    
   
    ResistorValue.setText(" ");
    ResistorTol.setText(" ");
    MinimumRange.setText(" ");
    MaximumRange.setText(" ");
    
    Fnumber = " " ;
    Snumber = " " ;
    Multiplier = " ";
    Tolerance = " ";
    
   
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed

        try{
        String FSNumber = Fnumber + Snumber;
        double digit= Double.parseDouble(FSNumber);
        double multiplier = Double.parseDouble(Multiplier);
        double tolerance = Double.parseDouble(Tolerance);
        
       double RVal = (digit * multiplier);
       double RTol = (RVal * tolerance);
       double MinRange = RVal - RTol;
       double MaxRange = RVal + RTol;
       
        ResistorValue.setText(String.format("%.4fK Ohm", RVal/1000));
        ResistorTol.setText(String.format("%.4fK Ohm", RTol/1000));
        MinimumRange.setText(String.format("%.4fK ohm", MinRange/1000));
        MaximumRange.setText(String.format("%.4fK ohm", MaxRange/1000));
         
        Selector.setText("Done!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
     
    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void BlackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackButtonActionPerformed
       
        if(Fnumber.equals(" ")){
            Fnumber = "0";
            LBand1.setBackground(Color.BLACK);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "0";
            LBand2.setBackground(Color.BLACK);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "1";
            LBand3.setBackground(Color.BLACK);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
        else  if(Tolerance.equals(" ")){
            Tolerance = "0";
           LBand4.setBackground(Color.BLACK);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
     
    }//GEN-LAST:event_BlackButtonActionPerformed

    private void BrownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrownButtonActionPerformed
        
        if(Fnumber.equals(" ")){
            Fnumber = "1";
            LBand1.setBackground(Color.PINK);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "1";
            LBand2.setBackground(Color.PINK);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "10";
            LBand3.setBackground(Color.PINK);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.01";
           LBand4.setBackground(Color.PINK);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
     
    }//GEN-LAST:event_BrownButtonActionPerformed

    private void RedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedButtonActionPerformed
         if(Fnumber.equals(" ")){
            Fnumber = "2";
            LBand1.setBackground(Color.RED);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "2";
            LBand2.setBackground(Color.RED);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "100";
            LBand3.setBackground(Color.RED);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.02";
           LBand4.setBackground(Color.RED);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_RedButtonActionPerformed

    private void OrangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrangeButtonActionPerformed
         if(Fnumber.equals(" ")){
            Fnumber = "3";
            LBand1.setBackground(Color.ORANGE);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "3";
            LBand2.setBackground(Color.ORANGE);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "1000";
            LBand3.setBackground(Color.ORANGE);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.0005";
           LBand4.setBackground(Color.ORANGE);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_OrangeButtonActionPerformed

    private void YellowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YellowButtonActionPerformed
         if(Fnumber.equals(" ")){
            Fnumber = "4";
            LBand1.setBackground(Color.YELLOW);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "4";
            LBand2.setBackground(Color.YELLOW);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "10000";
            LBand3.setBackground(Color.YELLOW);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.0002";
           LBand4.setBackground(Color.YELLOW);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_YellowButtonActionPerformed

    private void GreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenButtonActionPerformed
      if(Fnumber.equals(" ")){
            Fnumber = "5";
            LBand1.setBackground(Color.GREEN);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "5";
            LBand2.setBackground(Color.GREEN);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "100000";
            LBand3.setBackground(Color.GREEN);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.005";
           LBand4.setBackground(Color.GREEN);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_GreenButtonActionPerformed

    private void BlueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueButtonActionPerformed
        if(Fnumber.equals(" ")){
            Fnumber = "6";
            LBand1.setBackground(Color.BLUE);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "6";
            LBand2.setBackground(Color.BLUE);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "1000000";
            LBand3.setBackground(Color.BLUE);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.0025";
           LBand4.setBackground(Color.BLUE);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_BlueButtonActionPerformed

    private void VioletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VioletButtonActionPerformed
         if(Fnumber.equals(" ")){
            Fnumber = "7";
            LBand1.setBackground(Color.magenta);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "7";
            LBand2.setBackground(Color.magenta);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "10000000";
            LBand3.setBackground(Color.magenta);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.001";
           LBand4.setBackground(Color.magenta);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_VioletButtonActionPerformed

    private void GrayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayButtonActionPerformed
 if(Fnumber.equals(" ")){
            Fnumber = "8";
            LBand1.setBackground(Color.GRAY);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "8";
            LBand2.setBackground(Color.GRAY);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "100000000";
            LBand3.setBackground(Color.GRAY);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        else  if(Tolerance.equals(" ")){
            Tolerance = "0.0001";
           LBand4.setBackground(Color.GRAY);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }    }//GEN-LAST:event_GrayButtonActionPerformed

    private void WhiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhiteButtonActionPerformed
         if(Fnumber.equals(" ")){
            Fnumber = "9";
            LBand1.setBackground(Color.WHITE);
            LBand1.setOpaque(true);
            Selector.setText("Choose Second Colour");
           }
        
        else  if(Snumber.equals(" ")){
            Snumber = "9";
            LBand2.setBackground(Color.WHITE);
            LBand2.setOpaque(true);
            Selector.setText("Choose Third Colour");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "1000000000";
            LBand3.setBackground(Color.WHITE);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
        
        else  if(Tolerance.equals(" ")){
            Tolerance = "0";
           LBand4.setBackground(Color.WHITE);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
     
    }//GEN-LAST:event_WhiteButtonActionPerformed

    private void GoldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoldButtonActionPerformed
         
         if(Fnumber.equals(" ")){
            JOptionPane.showMessageDialog(this,"Gold cannot be used for first colur");
           }
        
        else  if(Snumber.equals(" ")){
           JOptionPane.showMessageDialog(this,"Gold cannot be used for second colur");
            }
     
         
        else  if(Multiplier.equals(" ")){
            Multiplier = "0.1";
            LBand3.setBackground(Color.orange);
            LBand3.setOpaque(true);
            Selector.setText("Choose Fourth Colour");
            }
        
         
         
         else  if(Tolerance.equals(" ")){
            Tolerance = "0.05";
           LBand4.setBackground(Color.orange);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
     
    }//GEN-LAST:event_GoldButtonActionPerformed

    private void SilverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilverButtonActionPerformed
        if(Fnumber.equals(" ")){
            JOptionPane.showMessageDialog(this,"Silver cannot be used for first colur");
           }
        
        else  if(Snumber.equals(" ")){
           JOptionPane.showMessageDialog(this,"Silver cannot be used for second colur");
            }
     
       else  if(Multiplier.equals(" ")){
     JOptionPane.showMessageDialog(this,"Silver colour cannot be used for third colur");

            }
        
         
         
         else  if(Tolerance.equals(" ")){
            Tolerance = "0.1";
           LBand4.setBackground(Color.LIGHT_GRAY);
            LBand4.setOpaque(true);
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_SilverButtonActionPerformed

    private void NoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoneButtonActionPerformed
       if(Fnumber.equals(" ")){
            JOptionPane.showMessageDialog(this,"None colour cannot be used for first colur");
           }
        
        else  if(Snumber.equals(" ")){
           JOptionPane.showMessageDialog(this,"None colour cannot be used for second colur");
            }
     
         
        else  if(Multiplier.equals(" ")){
     JOptionPane.showMessageDialog(this,"None colour cannot be used for third colur");

            }
        
         
         
         else  if(Tolerance.equals(" ")){
            Tolerance = "0.2";
            Selector.setText("Click On Calculate");
            }
    }//GEN-LAST:event_NoneButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        frame = new JFrame();
 if(JOptionPane.showConfirmDialog(frame, "Do you want to exit from this page?", "Exit",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
     { setVisible(false); 
       
    }//GEN-LAST:event_ExitButtonActionPerformed
    }
    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       Help h = new Help();
       h.setVisible(true);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ResistanceToColor rtoC = new ResistanceToColor();
        rtoC.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         Help h = new Help();
       h.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorToResistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorToResistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorToResistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorToResistance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorToResistance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackButton;
    private javax.swing.JButton BlueButton;
    private javax.swing.JButton BrownButton;
    private javax.swing.JButton CalculateButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton GoldButton;
    private javax.swing.JButton GrayButton;
    private javax.swing.JButton GreenButton;
    private javax.swing.JLabel LBand1;
    private javax.swing.JLabel LBand2;
    private javax.swing.JLabel LBand3;
    private javax.swing.JLabel LBand4;
    private javax.swing.JTextField MaximumRange;
    private javax.swing.JTextField MinimumRange;
    private javax.swing.JButton NoneButton;
    private javax.swing.JButton OrangeButton;
    private javax.swing.JButton RedButton;
    private javax.swing.JTextField ResistorTol;
    private javax.swing.JTextField ResistorValue;
    private javax.swing.JTextField Selector;
    private javax.swing.JButton SilverButton;
    private javax.swing.JButton VioletButton;
    private javax.swing.JButton WhiteButton;
    private javax.swing.JButton YellowButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
