
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class ResistanceToColor extends javax.swing.JFrame {
      private JFrame frame;
      private int Fnum;
      private int Snum;
      private int val;
      private double doubleval = 0.0;
      private  int x;
      private int y;
      private int z;
      private int Multiplier;
      private double Tolerance;
      
     
    public ResistanceToColor() {
        
        super("Resistance Value To Colour");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ShowButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        LBand1 = new javax.swing.JLabel();
        LBand2 = new javax.swing.JLabel();
        LBand3 = new javax.swing.JLabel();
        LBand4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RValueTF = new javax.swing.JTextField();
        ShowTolerance = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4), "Resistance To Colour", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Algerian", 0, 18), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        ShowButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowButton.setText("Show Resistor");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Resistor Value by Ohm");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        LBand3.setBackground(new java.awt.Color(255, 255, 102));

        LBand4.setBackground(new java.awt.Color(204, 255, 153));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/TheResistor - cc.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LBand1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(LBand4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(LBand2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(LBand3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBand1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBand4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBand2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBand3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );

        RValueTF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ShowTolerance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowTolerance.setText("Show only tolerance");
        ShowTolerance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowToleranceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ShowTolerance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RValueTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RValueTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(ShowButton)
                        .addGap(18, 18, 18)
                        .addComponent(ShowTolerance)
                        .addGap(5, 5, 5))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Go To  Colour To Resistance Calculator");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem5.setText("Help");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Delete.png"))); // NOI18N
        jMenuItem2.setText("Close All Program");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      frame = new JFrame();
    if(JOptionPane.showConfirmDialog(frame, "Do you want to exit from this page?", "Exit",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
   {  setVisible(false); 
       
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
     
        try{
          
     doubleval = Double.parseDouble(RValueTF.getText());
     val = (int)doubleval;
     double a = 1 * Math.pow(10,10);
     double b = 1 * Math.pow(10,9);
      
    
       if(doubleval >= 1 * Math.pow(10,11)){
           
       LBand3.setOpaque(false);
       JOptionPane.showMessageDialog(null,"The resistance value is too large!","Warning",JOptionPane.WARNING_MESSAGE);
       Fnum = -1;
       Snum = -1;
       Tolerance = -1;
       Multiplier = 0;
       }
       
      else if(doubleval == 0){
      JOptionPane.showMessageDialog(null,"The resistance value is zero!","Warning",JOptionPane.WARNING_MESSAGE);   
       Fnum = -1;
       Snum = -1;
       Tolerance = -1;
       Multiplier = 0;
       }
       
       else if (val < 0){
         
       JOptionPane.showMessageDialog(null,"The resistance cannot be negative!","Warning",JOptionPane.WARNING_MESSAGE); 
        Fnum = -1;
        Snum = -1;
        Multiplier = 0;
        Tolerance = -1;

       }
           
       else if(doubleval >= a)// 10 zeroes
       {
           Fnum = (int)(doubleval/a);
           x = (int)(doubleval/b);
           Snum = x%10;
           Multiplier = 1000000000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
    else  if(doubleval >= b)// 9 zeroes
       {
           Fnum =(int) (val/b);
           x = val/100000000;
           Snum = x%10;
           Multiplier = 100000000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
       
      
            else if(val >= 100000000)// 8 zeroes
       {
           Fnum = val/100000000;
           x = val/10000000;
           Snum = x%10;
           Multiplier = 10000000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
             else if(val >= 10000000)// 7 zeroes
       {
           Fnum = val/10000000;
           x = val/1000000;
           Snum = x%10;
           Multiplier = 1000000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
            
            
              else if(val >= 1000000)// 6 zeroes
       {
           Fnum = val/1000000;
           x = val/100000;
           Snum = x%10;
           Multiplier = 100000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
       
          else if(val >= 100000)// 5zeroes
       {
           Fnum = val/100000;
           x = val/10000;
           Snum = x%10;
           Multiplier = 10000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
          
             else   if(val >= 10000)// 4 zeroes
       {
           Fnum = val/10000;
           x = val/1000;
           Snum = x%10;
           Multiplier = 1000;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       } 
             
               else   if(val >= 1000)// 3 zeroes
       {
           Fnum = val/1000;
           x = val/100;
           Snum = x%10;
           Multiplier = 100;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }                 
      
       
             else   if(val >= 100) //2
       {
           Fnum = val/100;
           x = val/10;
           Snum = x%10;
           Multiplier = 10;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
       
      else if(val >= 10) //1
       {
           Fnum = val/10;
          
               Snum = val%10;//different from the above conditions eg second number of 71 71%10 =1
           Multiplier = 1;
           y = val%Multiplier;
           z = val - y;
           Tolerance = (y*100.0)/z;
           
       }
     
      else if (val >= 1)
      {
       Fnum = val;
       Snum = 0;
       Multiplier = -1; // use -1 insted of 0.1 
       Tolerance = 1;//
      }
       
    
       else if(doubleval< 1)
       {
           Fnum = 0;
           double d = doubleval * 10;
         //int a = (int)doubleval;// to convert double to int.
         
       Snum = (int)d;
           Tolerance = 0.01;
           Multiplier = -1;//0.1
       }
        
      
     //black
     
      if( Fnum ==0 || Snum == 0 || Multiplier ==1 || Tolerance == 0)
       {
          if(Fnum ==0){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.BLACK);}
          if(Snum == 0){
            LBand2.setOpaque(rootPaneCheckingEnabled);
            LBand2.setBackground(Color.BLACK);
           }
           if(Multiplier == 1){
             LBand3.setOpaque(rootPaneCheckingEnabled);
             LBand3.setBackground(Color.BLACK);
           }
           if(Tolerance == 0)
           {
             LBand4.setOpaque(true);
             LBand4.setBackground(Color.BLACK);
           }
       }
       
       // brown
       if(Fnum == 1 || Snum == 1 || Multiplier == 10 || (Tolerance > 0.5 && Tolerance < 2))
       {
           if (Fnum ==1){
            LBand1.setOpaque(rootPaneCheckingEnabled);
            LBand1.setBackground(Color.PINK);}
           if(Snum == 1){
             LBand2.setOpaque(rootPaneCheckingEnabled);
             LBand2.setBackground(Color.PINK);}
           if(Multiplier == 10){
             LBand3.setOpaque(rootPaneCheckingEnabled);
             LBand3.setBackground(Color.PINK);}
           if(Tolerance > 0.5 && Tolerance < 2){
             LBand4.setOpaque(rootPaneCheckingEnabled);
             LBand4.setBackground(Color.PINK);
           }
       }
      //red
     if (Fnum == 2 || Snum == 2 || Multiplier == 100 || (Tolerance > 1 && Tolerance < 5))
       {
          if (Fnum ==2){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.RED);}
         if(Snum == 2){
            LBand2.setOpaque(rootPaneCheckingEnabled);
            LBand2.setBackground(Color.RED);}
          if(Multiplier == 100){
            LBand3.setOpaque(rootPaneCheckingEnabled);
            LBand3.setBackground(Color.RED);}
           if(Tolerance > 1 && Tolerance < 5){
            LBand4.setOpaque(rootPaneCheckingEnabled);
            LBand4.setBackground(Color.RED);
           }
       }
       //orange
       if (Fnum == 3 || Snum == 3 || Multiplier == 1000 || (Tolerance > 0.02 && Tolerance < 0.1))
       {
     
          if (Fnum ==3){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.ORANGE);}
          if(Snum == 3){
            LBand2.setOpaque(rootPaneCheckingEnabled);
            LBand2.setBackground(Color.ORANGE);}
          if(Multiplier == 1000){
            LBand3.setOpaque(rootPaneCheckingEnabled);
            LBand3.setBackground(Color.ORANGE);}
           if(Tolerance > 0.02 && Tolerance < 0.1){
             LBand4.setOpaque(rootPaneCheckingEnabled);
             LBand4.setBackground(Color.ORANGE);}
           
       }
       
       //yellow
        if(Fnum == 4 || Snum == 4 || Multiplier == 10000 || (Tolerance > 0.01 && Tolerance < 0.05))
       {
       
          if (Fnum ==4){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.YELLOW);}
          if(Snum == 4){
            LBand2.setBackground(Color.YELLOW);
            LBand2.setOpaque(rootPaneCheckingEnabled);}
           if(Multiplier == 10000){
            LBand3.setOpaque(rootPaneCheckingEnabled);
            LBand3.setBackground(Color.YELLOW);}
           if(Tolerance > 0.02 && Tolerance < 0.1){
            LBand4.setOpaque(rootPaneCheckingEnabled);
            LBand4.setBackground(Color.YELLOW);
           }
       }
        //Green
         if(Fnum == 5 || Snum == 5 || Multiplier == 100000 || (Tolerance >0.25 && Tolerance < 1))
       { 
       
         if (Fnum ==5){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.GREEN);}
          if(Snum == 5){
           LBand2.setOpaque(rootPaneCheckingEnabled);
           LBand2.setBackground(Color.GREEN);}
          if(Multiplier == 100000){
           LBand3.setOpaque(rootPaneCheckingEnabled);
           LBand3.setBackground(Color.GREEN);}
          if(Tolerance >0.25 && Tolerance < 1){
           LBand4.setOpaque(rootPaneCheckingEnabled);
           LBand4.setBackground(Color.GREEN);}
           
       }
         
         //Blue
        if (Fnum == 6 || Snum == 6 || Multiplier == 1000000 || (Tolerance >0.1 && Tolerance < 0.5))
       {
       
                
         if (Fnum ==6){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.BLUE);}
         if(Snum == 6){
            LBand2.setOpaque(rootPaneCheckingEnabled);
            LBand2.setBackground(Color.BLUE);}
         if(Multiplier == 1000000){
            LBand3.setOpaque(rootPaneCheckingEnabled);
            LBand3.setBackground(Color.BLUE);}
         if(Tolerance >0.1 && Tolerance < 0.5){
            LBand4.setOpaque(rootPaneCheckingEnabled);
            LBand4.setBackground(Color.BLUE);}
           
       }
           
           //violet
         
      if(Fnum == 7 || Snum == 7 || Multiplier == 10000000 || (Tolerance >0.05 && Tolerance < 0.25))
       {
               
         if (Fnum ==7){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.magenta);}
         if(Snum == 7){
            LBand2.setOpaque(rootPaneCheckingEnabled);
            LBand2.setBackground(Color.magenta);}
         if(Multiplier == 10000000){
            LBand3.setOpaque(rootPaneCheckingEnabled);
            LBand3.setBackground(Color.magenta);}
         if(Tolerance >0.05 && Tolerance < 0.25){
             LBand4.setOpaque(rootPaneCheckingEnabled);
             LBand4.setBackground(Color.magenta);}
           
       }
       
       //Grey
      if(Fnum == 8 || Snum == 8 || Multiplier == 100000000 || (Tolerance >0 && Tolerance < 0.2))
       {
           
        if (Fnum ==8){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.gray);}
        if(Snum == 8){
           LBand2.setOpaque(rootPaneCheckingEnabled);
           LBand2.setBackground(Color.gray);}
        if(Multiplier == 100000000){
           LBand3.setOpaque(rootPaneCheckingEnabled);
           LBand3.setBackground(Color.gray);}
        if(Tolerance >0 && Tolerance < 0.2){
           LBand4.setOpaque(rootPaneCheckingEnabled); 
           LBand4.setBackground(Color.gray);}
           
       }
           
          //white
     if(Fnum == 9 || Snum == 9 || Multiplier == 1000000000 )
       {
        if (Fnum ==9){
           LBand1.setOpaque(rootPaneCheckingEnabled);
           LBand1.setBackground(Color.white);}
         if(Snum == 9){
           LBand2.setOpaque(rootPaneCheckingEnabled);
           LBand2.setBackground(Color.white);}
         if(Multiplier == 1000000000){
           LBand3.setOpaque(rootPaneCheckingEnabled);
           LBand3.setBackground(Color.white);
           }
           
       }
              
              //gold
    if( Multiplier == -1 || (Tolerance >10 && Tolerance < 2))//-1 = 0.1
       {
    
      if(Multiplier == -1){
        LBand3.setOpaque(rootPaneCheckingEnabled);
        LBand3.setBackground(Color.orange);}
      if(Tolerance >10 && Tolerance < 2){
       LBand4.setOpaque(rootPaneCheckingEnabled);
       LBand4.setBackground(Color.orange);}
           
       }
                  
              //silver
                  
      if((Tolerance >5 && Tolerance < 20))//-1 = 0.1
       {
        if(Tolerance >5 && Tolerance < 20){
         LBand4.setOpaque(rootPaneCheckingEnabled);    
         LBand4.setBackground(Color.lightGray);}
           
       }     
     //none
               
      if(Tolerance >20)//no colour
       {
         
           
       } 
        
    }
      catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Help h = new Help();
       h.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ColorToResistance CtoR = new ColorToResistance();
       CtoR.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
    RValueTF.setText(" ");
    LBand1.setOpaque(false);
    LBand1.setBackground(Color.CYAN);
    LBand2.setOpaque(false);
    LBand2.setBackground(Color.CYAN);
    LBand3.setOpaque(false);
    LBand3.setBackground(Color.CYAN);
    LBand4.setOpaque(false);
    LBand4.setBackground(Color.CYAN);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ShowToleranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowToleranceActionPerformed
       JOptionPane.showMessageDialog(this,"0.001% --> Gray \n0.1% -----> Violet \n0.5% -----> Green \n1% ------> Brown "
               + " \n2% ------> Red \n5% ------> Gold \n10% -----> Silver \n20% -----> None ");
    }//GEN-LAST:event_ShowToleranceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResistanceToColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResistanceToColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResistanceToColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResistanceToColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResistanceToColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBand1;
    private javax.swing.JLabel LBand2;
    private javax.swing.JLabel LBand3;
    private javax.swing.JLabel LBand4;
    private javax.swing.JTextField RValueTF;
    private javax.swing.JButton ShowButton;
    private javax.swing.JButton ShowTolerance;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
